# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_packet_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import msg_error_pb2
import msg_struct_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_packet_data.proto',
  package='msg',
  serialized_pb=_b('\n\x15msg_packet_data.proto\x12\x03msg\x1a\x0fmsg_error.proto\x1a\x10msg_struct.proto\"2\n\x0bsign_up_req\x12\x11\n\tuseremail\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\"A\n\x0bsign_up_ack\x12\x1f\n\x08\x65rr_code\x18\x01 \x02(\x0e\x32\r.msg.err_type\x12\x11\n\tauthtoken\x18\x02 \x02(\t\"2\n\x0bsign_in_req\x12\x11\n\tuseremail\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\"A\n\x0bsign_in_ack\x12\x1f\n\x08\x65rr_code\x18\x01 \x02(\x0e\x32\r.msg.err_type\x12\x11\n\tauthtoken\x18\x02 \x02(\t\"N\n\x14\x63reate_character_req\x12\x11\n\tauthtoken\x18\x01 \x02(\t\x12\x10\n\x08\x63har_mid\x18\x02 \x02(\x05\x12\x11\n\tchar_name\x18\x03 \x02(\t\"Z\n\x14\x63reate_character_ack\x12\x1f\n\x08\x65rr_code\x18\x01 \x02(\x0e\x32\r.msg.err_type\x12!\n\tchar_list\x18\x02 \x03(\x0b\x32\x0e.msg.char_info\"&\n\x11get_char_list_req\x12\x11\n\tauthtoken\x18\x01 \x02(\t\"W\n\x11get_char_list_ack\x12\x1f\n\x08\x65rr_code\x18\x01 \x02(\x0e\x32\r.msg.err_type\x12!\n\tchar_list\x18\x02 \x03(\x0b\x32\x0e.msg.char_info')
  ,
  dependencies=[msg_error_pb2.DESCRIPTOR,msg_struct_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SIGN_UP_REQ = _descriptor.Descriptor(
  name='sign_up_req',
  full_name='msg.sign_up_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='useremail', full_name='msg.sign_up_req.useremail', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='msg.sign_up_req.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=115,
)


_SIGN_UP_ACK = _descriptor.Descriptor(
  name='sign_up_ack',
  full_name='msg.sign_up_ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_code', full_name='msg.sign_up_ack.err_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='authtoken', full_name='msg.sign_up_ack.authtoken', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=182,
)


_SIGN_IN_REQ = _descriptor.Descriptor(
  name='sign_in_req',
  full_name='msg.sign_in_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='useremail', full_name='msg.sign_in_req.useremail', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='msg.sign_in_req.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=234,
)


_SIGN_IN_ACK = _descriptor.Descriptor(
  name='sign_in_ack',
  full_name='msg.sign_in_ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_code', full_name='msg.sign_in_ack.err_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='authtoken', full_name='msg.sign_in_ack.authtoken', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=301,
)


_CREATE_CHARACTER_REQ = _descriptor.Descriptor(
  name='create_character_req',
  full_name='msg.create_character_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='authtoken', full_name='msg.create_character_req.authtoken', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='char_mid', full_name='msg.create_character_req.char_mid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='char_name', full_name='msg.create_character_req.char_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=381,
)


_CREATE_CHARACTER_ACK = _descriptor.Descriptor(
  name='create_character_ack',
  full_name='msg.create_character_ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_code', full_name='msg.create_character_ack.err_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='char_list', full_name='msg.create_character_ack.char_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=473,
)


_GET_CHAR_LIST_REQ = _descriptor.Descriptor(
  name='get_char_list_req',
  full_name='msg.get_char_list_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='authtoken', full_name='msg.get_char_list_req.authtoken', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=475,
  serialized_end=513,
)


_GET_CHAR_LIST_ACK = _descriptor.Descriptor(
  name='get_char_list_ack',
  full_name='msg.get_char_list_ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_code', full_name='msg.get_char_list_ack.err_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='char_list', full_name='msg.get_char_list_ack.char_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=602,
)

_SIGN_UP_ACK.fields_by_name['err_code'].enum_type = msg_error_pb2._ERR_TYPE
_SIGN_IN_ACK.fields_by_name['err_code'].enum_type = msg_error_pb2._ERR_TYPE
_CREATE_CHARACTER_ACK.fields_by_name['err_code'].enum_type = msg_error_pb2._ERR_TYPE
_CREATE_CHARACTER_ACK.fields_by_name['char_list'].message_type = msg_struct_pb2._CHAR_INFO
_GET_CHAR_LIST_ACK.fields_by_name['err_code'].enum_type = msg_error_pb2._ERR_TYPE
_GET_CHAR_LIST_ACK.fields_by_name['char_list'].message_type = msg_struct_pb2._CHAR_INFO
DESCRIPTOR.message_types_by_name['sign_up_req'] = _SIGN_UP_REQ
DESCRIPTOR.message_types_by_name['sign_up_ack'] = _SIGN_UP_ACK
DESCRIPTOR.message_types_by_name['sign_in_req'] = _SIGN_IN_REQ
DESCRIPTOR.message_types_by_name['sign_in_ack'] = _SIGN_IN_ACK
DESCRIPTOR.message_types_by_name['create_character_req'] = _CREATE_CHARACTER_REQ
DESCRIPTOR.message_types_by_name['create_character_ack'] = _CREATE_CHARACTER_ACK
DESCRIPTOR.message_types_by_name['get_char_list_req'] = _GET_CHAR_LIST_REQ
DESCRIPTOR.message_types_by_name['get_char_list_ack'] = _GET_CHAR_LIST_ACK

sign_up_req = _reflection.GeneratedProtocolMessageType('sign_up_req', (_message.Message,), dict(
  DESCRIPTOR = _SIGN_UP_REQ,
  __module__ = 'msg_packet_data_pb2'
  # @@protoc_insertion_point(class_scope:msg.sign_up_req)
  ))
_sym_db.RegisterMessage(sign_up_req)

sign_up_ack = _reflection.GeneratedProtocolMessageType('sign_up_ack', (_message.Message,), dict(
  DESCRIPTOR = _SIGN_UP_ACK,
  __module__ = 'msg_packet_data_pb2'
  # @@protoc_insertion_point(class_scope:msg.sign_up_ack)
  ))
_sym_db.RegisterMessage(sign_up_ack)

sign_in_req = _reflection.GeneratedProtocolMessageType('sign_in_req', (_message.Message,), dict(
  DESCRIPTOR = _SIGN_IN_REQ,
  __module__ = 'msg_packet_data_pb2'
  # @@protoc_insertion_point(class_scope:msg.sign_in_req)
  ))
_sym_db.RegisterMessage(sign_in_req)

sign_in_ack = _reflection.GeneratedProtocolMessageType('sign_in_ack', (_message.Message,), dict(
  DESCRIPTOR = _SIGN_IN_ACK,
  __module__ = 'msg_packet_data_pb2'
  # @@protoc_insertion_point(class_scope:msg.sign_in_ack)
  ))
_sym_db.RegisterMessage(sign_in_ack)

create_character_req = _reflection.GeneratedProtocolMessageType('create_character_req', (_message.Message,), dict(
  DESCRIPTOR = _CREATE_CHARACTER_REQ,
  __module__ = 'msg_packet_data_pb2'
  # @@protoc_insertion_point(class_scope:msg.create_character_req)
  ))
_sym_db.RegisterMessage(create_character_req)

create_character_ack = _reflection.GeneratedProtocolMessageType('create_character_ack', (_message.Message,), dict(
  DESCRIPTOR = _CREATE_CHARACTER_ACK,
  __module__ = 'msg_packet_data_pb2'
  # @@protoc_insertion_point(class_scope:msg.create_character_ack)
  ))
_sym_db.RegisterMessage(create_character_ack)

get_char_list_req = _reflection.GeneratedProtocolMessageType('get_char_list_req', (_message.Message,), dict(
  DESCRIPTOR = _GET_CHAR_LIST_REQ,
  __module__ = 'msg_packet_data_pb2'
  # @@protoc_insertion_point(class_scope:msg.get_char_list_req)
  ))
_sym_db.RegisterMessage(get_char_list_req)

get_char_list_ack = _reflection.GeneratedProtocolMessageType('get_char_list_ack', (_message.Message,), dict(
  DESCRIPTOR = _GET_CHAR_LIST_ACK,
  __module__ = 'msg_packet_data_pb2'
  # @@protoc_insertion_point(class_scope:msg.get_char_list_ack)
  ))
_sym_db.RegisterMessage(get_char_list_ack)


# @@protoc_insertion_point(module_scope)
