# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_enum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_enum.proto',
  package='msg',
  serialized_pb=_b('\n\x0emsg_enum.proto\x12\x03msg*\x1e\n\rplatform_type\x12\r\n\tplat_none\x10\x00*A\n\nactor_type\x12\x0e\n\nact_player\x10\x01\x12\x0f\n\x0b\x61\x63t_monster\x10\x02\x12\x12\n\x0e\x61\x63t_interactor\x10\x03*7\n\x0c\x61\x63tor_status\x12\x0c\n\x08is_alive\x10\x01\x12\x0c\n\x08is_dying\x10\x02\x12\x0b\n\x07is_dead\x10\x03*Y\n\tpart_type\x12\r\n\tpart_none\x10\x00\x12\x0f\n\x0bpart_weapon\x10\x01\x12\r\n\tpart_head\x10\x03\x12\r\n\tpart_body\x10\x02\x12\x0e\n\npart_wings\x10\x04')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PLATFORM_TYPE = _descriptor.EnumDescriptor(
  name='platform_type',
  full_name='msg.platform_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='plat_none', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=23,
  serialized_end=53,
)
_sym_db.RegisterEnumDescriptor(_PLATFORM_TYPE)

platform_type = enum_type_wrapper.EnumTypeWrapper(_PLATFORM_TYPE)
_ACTOR_TYPE = _descriptor.EnumDescriptor(
  name='actor_type',
  full_name='msg.actor_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='act_player', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='act_monster', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='act_interactor', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=55,
  serialized_end=120,
)
_sym_db.RegisterEnumDescriptor(_ACTOR_TYPE)

actor_type = enum_type_wrapper.EnumTypeWrapper(_ACTOR_TYPE)
_ACTOR_STATUS = _descriptor.EnumDescriptor(
  name='actor_status',
  full_name='msg.actor_status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='is_alive', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='is_dying', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='is_dead', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=122,
  serialized_end=177,
)
_sym_db.RegisterEnumDescriptor(_ACTOR_STATUS)

actor_status = enum_type_wrapper.EnumTypeWrapper(_ACTOR_STATUS)
_PART_TYPE = _descriptor.EnumDescriptor(
  name='part_type',
  full_name='msg.part_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='part_none', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='part_weapon', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='part_head', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='part_body', index=3, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='part_wings', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=179,
  serialized_end=268,
)
_sym_db.RegisterEnumDescriptor(_PART_TYPE)

part_type = enum_type_wrapper.EnumTypeWrapper(_PART_TYPE)
plat_none = 0
act_player = 1
act_monster = 2
act_interactor = 3
is_alive = 1
is_dying = 2
is_dead = 3
part_none = 0
part_weapon = 1
part_head = 3
part_body = 2
part_wings = 4


DESCRIPTOR.enum_types_by_name['platform_type'] = _PLATFORM_TYPE
DESCRIPTOR.enum_types_by_name['actor_type'] = _ACTOR_TYPE
DESCRIPTOR.enum_types_by_name['actor_status'] = _ACTOR_STATUS
DESCRIPTOR.enum_types_by_name['part_type'] = _PART_TYPE


# @@protoc_insertion_point(module_scope)
