# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_type_channel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_type_channel.proto',
  package='msg',
  serialized_pb=_b('\n\x16msg_type_channel.proto\x12\x03msg*;\n\ttype_play\x12\x16\n\x10t_enter_town_req\x10\x89\xa4\x01\x12\x16\n\x10t_enter_town_ack\x10\x8a\xa4\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TYPE_PLAY = _descriptor.EnumDescriptor(
  name='type_play',
  full_name='msg.type_play',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='t_enter_town_req', index=0, number=21001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='t_enter_town_ack', index=1, number=21002,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=31,
  serialized_end=90,
)
_sym_db.RegisterEnumDescriptor(_TYPE_PLAY)

type_play = enum_type_wrapper.EnumTypeWrapper(_TYPE_PLAY)
t_enter_town_req = 21001
t_enter_town_ack = 21002


DESCRIPTOR.enum_types_by_name['type_play'] = _TYPE_PLAY


# @@protoc_insertion_point(module_scope)
